name: Check that `make build` does not produce additional changes
on:
  pull_request:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install pybase16
        run: pip install pybase16-builder
      - name: Fetch the repository code
        uses: actions/checkout@v2
      - name: Run make
        run: make
      - name: Check if there are changes
        run: git diff --exit-code
